import Head from 'next/head'
import { Inter } from '@next/font/google'
import Layout from 'components/layout'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout>
				<div className="bg-slate-300 h-screen">
					<main className={inter.className}>
						<div className='mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 pt-20 pb-16 text-center lg:pt-32'>
							<ul className='flex flex-col gap-5'>
								<li>Use a mix of uppercase and lowercase letters, numbers, and symbols.</li>
								<li>Use a minimum of 8 characters, but longer is better</li>
								<li>Avoid using common words, phrases, or patterns that can be easily guessed (such as "password", "123456", or "qwerty").</li>
								<li>Use a combination of random words, rather than a single word or phrase.</li>
								<li>Don't reuse the same password for multiple accounts.</li>
								<li>Use a password manager to generate and store unique, strong passwords for each account.</li>
								<li>Avoid using personal information such as your name, birthdate, or address in your password.</li>
								<li>Avoid using consecutive characters on the keyboard (such as "asdf" or "zxcv").</li>
								<li>Use a passphrase or sentence that's easy for you to remember, but difficult for others to guess.</li>
								<li>Update your passwords regularly (every 3-6 months), especially for sensitive accounts like banking or email.</li>
							</ul>
						</div>
					</main>
				</div>
			</Layout>
		</>
	)
}
